name: conc
on: push
jobs:
  normal-job:
    runs-on: ubuntu-latest
    steps:
      - name: non-con-task
        run: |
          echo "hi"
          echo ${{ github.sha }}
          echo ${{ vars.allowedLocation }}
          echo "hello"