name: conc
on: push
jobs:
  normal-job:
    runs-on: ubuntu-latest
    steps:
      - name: non-con-task
        run: echo "hi"
  conc-job:
    needs: normal-job
    concurrency: 
      group: prod
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: task1
        run: |
          echo "hi"
          sleep 20
          echo "hi"

#job123458