name: errorHandling
on: 
  push:
  workflow_dispatch:
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
     - name: successtask
       run: echo "success"
     - name: failuretask
       id: step2
       continue-on-error: true
       run: echo "failed
     - name: taskafterfailure
       run: |
         echo "task after failure"
         echo "${{steps.step2.conclusion}}"




       
